#!/usr/bin/env node
// Fetch KanjiVG stroke paths for hiragana and write a TypeScript file
// at data/curriculum/ja/strokeData.ts.
//
// KanjiVG is CC BY-SA 3.0 (https://kanjivg.tagaini.net).
//
// Usage:
//   node scripts/fetch-strokes.mjs              # default: all hiragana
//   node scripts/fetch-strokes.mjs あいう       # specific chars
//
// Requires Node 18+ for global fetch.

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const OUTFILE = resolve(__dirname, "..", "data", "curriculum", "ja", "strokeData.ts");

// Full hiragana set (excluding rare variants).
const ALL_HIRAGANA =
  "あいうえお" +
  "かきくけこ" +
  "さしすせそ" +
  "たちつてと" +
  "なにぬねの" +
  "はひふへほ" +
  "まみむめも" +
  "やゆよ" +
  "らりるれろ" +
  "わをん" +
  // Dakuten / handakuten
  "がぎぐげござじずぜぞだぢづでどばびぶべぼぱぴぷぺぽ" +
  // Common small kana
  "っゃゅょ";

const CHARS = process.argv[2] ? Array.from(process.argv[2]) : Array.from(ALL_HIRAGANA);

const HINTS_DEFAULT = { start: "Start as shown", direction: "Follow the curve" };

const ROMAJI = {
  あ: "a", い: "i", う: "u", え: "e", お: "o",
  か: "ka", き: "ki", く: "ku", け: "ke", こ: "ko",
  さ: "sa", し: "shi", す: "su", せ: "se", そ: "so",
  た: "ta", ち: "chi", つ: "tsu", て: "te", と: "to",
  な: "na", に: "ni", ぬ: "nu", ね: "ne", の: "no",
  は: "ha", ひ: "hi", ふ: "fu", へ: "he", ほ: "ho",
  ま: "ma", み: "mi", む: "mu", め: "me", も: "mo",
  や: "ya", ゆ: "yu", よ: "yo",
  ら: "ra", り: "ri", る: "ru", れ: "re", ろ: "ro",
  わ: "wa", を: "wo", ん: "n",
  が: "ga", ぎ: "gi", ぐ: "gu", げ: "ge", ご: "go",
  ざ: "za", じ: "ji", ず: "zu", ぜ: "ze", ぞ: "zo",
  だ: "da", ぢ: "ji", づ: "zu", で: "de", ど: "do",
  ば: "ba", び: "bi", ぶ: "bu", べ: "be", ぼ: "bo",
  ぱ: "pa", ぴ: "pi", ぷ: "pu", ぺ: "pe", ぽ: "po",
  っ: "(small tsu)", ゃ: "(small ya)", ゅ: "(small yu)", ょ: "(small yo)",
};

function codepointHex(ch) {
  return ch.codePointAt(0).toString(16).padStart(5, "0");
}

async function fetchSvg(ch) {
  const url = `https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/${codepointHex(ch)}.svg`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${ch}: HTTP ${res.status}`);
  return await res.text();
}

function parseStrokes(svg) {
  // Extract all <path id="kvg:..." d="..."/> entries. KanjiVG places per-stroke
  // path elements inside the SVG; the d attribute is what we want.
  const paths = [];
  const re = /<path[^>]*\sd="([^"]+)"/g;
  let m;
  while ((m = re.exec(svg))) {
    paths.push(m[1]);
  }
  return paths;
}

const results = {};
for (const ch of CHARS) {
  try {
    const svg = await fetchSvg(ch);
    const paths = parseStrokes(svg);
    if (paths.length === 0) {
      console.warn(`[warn] ${ch}: no <path> elements`);
      continue;
    }
    results[ch] = {
      char: ch,
      romaji: ROMAJI[ch] ?? "",
      strokes: paths.map((d) => ({ d, startHint: HINTS_DEFAULT.start, directionHint: HINTS_DEFAULT.direction })),
    };
    console.log(`[ok]  ${ch}  (${paths.length} stroke${paths.length === 1 ? "" : "s"})`);
  } catch (e) {
    console.warn(`[err] ${ch}: ${e.message}`);
  }
}

const ts = `// Stroke data for Japanese characters.
// Paths sourced from KanjiVG (https://kanjivg.tagaini.net), CC BY-SA 3.0.
// Generated by scripts/fetch-strokes.mjs — re-run to refresh.

export const STROKE_VIEWBOX = "0 0 109 109";

export interface StrokeData {
  d: string;
  startHint: string;
  directionHint: string;
  end?: { x: number; y: number };
}

export interface CharacterStrokeData {
  char: string;
  romaji: string;
  strokes: StrokeData[];
}

export const STROKE_DATA: Record<string, CharacterStrokeData> = ${JSON.stringify(results, null, 2)};

/** Extract the starting (M) point from an SVG path. */
export function getPathStart(d: string): { x: number; y: number } {
  const m = d.match(/M\\s*([\\d.]+)[,\\s]([\\d.]+)/);
  return m ? { x: parseFloat(m[1]), y: parseFloat(m[2]) } : { x: 0, y: 0 };
}
`;

writeFileSync(OUTFILE, ts, "utf8");
console.log(`\nWrote ${OUTFILE} with ${Object.keys(results).length} characters.`);
